### ISSUE TITLE
Adding ability to override default route generator OR skip page=1

### ISSUE THREAD

**Issue by zhil** [whiteoctober/WhiteOctoberPagerfantaBundle#128]
This is regarding #54 

I propose to add ability to skip page=1 parameter (with adding "fallback" route) OR give ability to override default route generator (which is [hardcoded now](https://github.com/whiteoctober/WhiteOctoberPagerfantaBundle/blob/master/Twig/PagerfantaExtension.php#L108) )

Let me know which one solution would be acceptable and I will create PR.

**Comment by zhil** [comment]
I have also added fallbackRouteName proposal, which could be the best choice
https://github.com/symfony/symfony/issues/16623

**Comment by zhil** [comment]
also covered by https://github.com/symfony/symfony/issues/5424

**Comment by pablodip** [comment]
Done on #131

**Comment by Lumbendil** [comment]
@pablodip this didn't actually solve the issue for people using custom routing (For instance, I paginate using either "/" or "/page2.html"). I had to revert to 1.0.4 due to that change.
